### ISSUE TITLE
Отсутствует файл info

### ISSUE THREAD

**Issue by Kirill** [Bashka/vim_start#1]
E484: Невозможно открыть файл C:\Users\kirill.vim\bundle\vim_start\plugin\vim_start\info
Нажмите ENTER или введите команду для продолжения                                          

Что это за нужный файл, который добавлен в gitignore?

**Comment by Bashka** [comment]
По хорошему это должен быть пустой файл, в котором построчно хранятся абсолютные адреса каталогов ваших проектов.

Добавил проверку на отсутствие этого файла и залил изменения. Обновитесь.

Учтите, что данные в этот файл (а значит, и в стартовое меню) добавляются не автоматически. Их надо либо добавить вручную (в файл info или нажав в стартовом меню Shift+e), либо использовать команду VimPrjCreate плагина vim_prj, при этом создастся новый проект, который будет добавлен в info.
