### ISSUE TITLE
Зависание MacVim при открытии проекта

### ISSUE THREAD

**Issue by SchDen** [Bashka/vim_start#2]
Добавил в конфиг фйл (через "E") путь к корню одного из проектов, - на стартовом экране появляется путь к проекту - при попытке открытия проекта через MacVim  происходит его полное зависание (см. скриншот). Клавиши ESC, CTRL+C, CTRL+Q - не дают никакого эффекта.
![2015-06-14 20 43 06](https://cloud.githubusercontent.com/assets/1484977/8149710/83993308-12d6-11e5-9729-028677f8cf2e.png)

Особенность в том, что в терминальном виме срабатывает нормально, - проект открывается.
P.S: Возможно проблема присутствует и в других версиях (gvim и тп)

**Comment by Bashka** [comment]
Поправил. Если обновите плагин vim_start, все должно работать корректно.
