### ISSUE TITLE
Куча ошибок при открытии проекта

### ISSUE THREAD

**Issue by gBopHuk** [Bashka/vim_start#3]
Получаю кучу ошибок при открытии проекта.
Ошибки такого вида

строка 2041:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead _.slt^I^I^Isetf tsalt
строка 2044:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead *.ti^I^I^Isetf terminfo
строка 2047:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead *.latex,_.sty,_.dtx,_.ltx,_.bbl^Isetf tex
строка 2048:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead *.tex^I^I^Icall s:FTtex()
строка 2103:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead tex/context/_/_.tex,_.mkii,_.mkiv   setf context
строка 2106:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead *.texinfo,_.texi,*.txi^Isetf texinfo
строка 2109:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead texmf.cnf^I^I^Isetf texmf
строка 2112:
E12: Команда не допускается в exrc/vimrc в текущем каталоге или поиске меток: au BufNewFile,BufRead .tidyrc,tidyrc^I^Isetf tidy
строка 2115:

Пока не разобрался как приложить полный лог

**Comment by Bashka** [comment]
Возможно сторонние плагины конфликтуют с vim_start (в vim_start нет перечисленных в логе au). Не могу повторить ошибку.

**Comment by gBopHuk** [comment]
Нашёл причину такого поведения:
Так влияет параметр set secure в .vimrc

**Comment by Bashka** [comment]
Добавил принудительное отключение опции secure при старте плагина vim_prj. Спасибо за помощь.
